receivers:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:

  batch:

  memory_limiter:
    check_interval: 1s
    limit_mib: 2000

exporters:

  debug:
    verbosity: detailed

  otlp/elastic:
    endpoint: "${env:APM_SERVER_HOST}"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [otlp/elastic]
