version: '3.8'

services:
  shard:
    extends:
      file: docker-compose.yml
      service: mongodb
    command: mongod --replSet shard --config /etc/mongod.conf
    volumes:
      - ./conf.d/mongod.shard.conf:/etc/mongod.conf

  shard-1:
    extends:
      service: shard
    container_name: shard-1
    environment:
      - REPLICA_ID=shard
      - REPLICA_CONFIG=false
      - REPLICA_MEMBERS=shard-1:27017,shard-2:27017,shard-3:27017
    volumes:
      - shard-1:/data/db
      - ./scripts/healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: ["CMD", "bash", "/healthcheck.sh"]
      interval: 5s
      retries: 10
    depends_on:
      shard-2: { condition: service_healthy }
      shard-3: { condition: service_healthy }

  shard-2:
    extends:
      service: shard
    container_name: shard-2
    volumes:
      - shard-2:/data/db

  shard-3:
    extends:
      service: shard
    container_name: shard-3
    volumes:
      - shard-3:/data/db
