version: '3.8'

services:
  mongos:
    extends:
      file: docker-compose.yml
      service: mongodb
    container_name: mongos
    command: mongos --config /etc/mongod.conf
    entrypoint: ["bash", "/docker-entrypoint.sh"]
    environment:
      - MONGO_PORT=${MONGOS_PORT:-27017}
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_DATABASE
      - MONGO_SHARDS=shard/shard-1:27017,shard/shard-2:27017,shard/shard-3:27017
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./conf.d/mongod.mongos.conf:/etc/mongod.conf
    depends_on:
      config-1: { condition: service_healthy }
      config-2: { condition: service_healthy }
      config-3: { condition: service_healthy }
      shard-1: { condition: service_healthy }
      shard-2: { condition: service_healthy }
      shard-3: { condition: service_healthy }
