version: '3.8'

services:

  config:
    extends:
      file: docker-compose.yml
      service: mongo
    command: mongod --replSet config --config /etc/mongod.conf
    volumes:
      - ./conf.d/mongod.config.conf:/etc/mongod.conf

  config-1:
    extends:
      service: config
    container_name: config-1
    environment:
      - REPLICA_ID=config
      - REPLICA_CONFIG=true
      - REPLICA_MEMBERS=config-1:27017,config-2:27017,config-3:27017
    volumes:
      - config-1:/data/db
      - ./scripts/healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: ["CMD", "bash", "/healthcheck.sh"]
      interval: 5s
      retries: 10
    depends_on:
      config-2: { condition: service_healthy }
      config-3: { condition: service_healthy }

  config-2:
    extends:
      service: config
    container_name: config-2
    volumes:
      - config-2:/data/db

  config-3:
    extends:
      service: config
    container_name: config-3
    volumes:
      - config-3:/data/db
