version: '3.9'

networks:
  haproxy:
    name: haproxy
    driver: overlay

x-tor: &tor
  build:
    context: ./tor
  image: tor:latest
  networks:
    - haproxy
  deploy:
    replicas: 8
    update_config:
      parallelism: 2
      delay: 10s
      failure_action: rollback
    restart_policy:
      condition: on-failure

services:
  haproxy:
    image: haproxy:latest
    ports:
      - "8050:8050"
      - "8051:8051"
      - "14567:14567"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - haproxy
    depends_on:
      - amazon
      - naver
    deploy:
      placement:
        constraints: [ node.role == manager ]

  amazon:
    << : *tor
    environment:
      EXIT_NODES: "{FI},{ES},{UK},{IE},{SG},{JP},{KR},{HK},{TW},{CA},{AU},{NZ},{AE},{QA},{IL},{TH},{VN},{BG},{LV},{EE}"

  naver:
    << : *tor
    environment:
      EXIT_NODES: "{JP},{KR}"
