version: '3.9'

networks:
  tor:
    name: tor
    driver: overlay

configs:
  haproxy:
    file: ./haproxy.cfg

services:
  haproxy:
    image: haproxy:latest
    ports:
      - "8050:8050"
      - "14567:14567"
    configs:
      - source: haproxy
        target: /usr/local/etc/haproxy/haproxy.cfg
    networks:
      - tor
    deploy:
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - tor

  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile
    image: tor:latest
    networks:
      - tor
    environment:
      - EXIT_NODES
    deploy:
      replicas: 8
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
