version: '3.9'

networks:
  tor:
    name: tor
    driver: bridge

services:
  # 네덜란드
  tor-nl:
    build:
      context: ./tor
    image: tor
    container_name: tor-nl
    restart: always
    networks:
      - tor
    environment:
      - INSTANCES=3
      - EXIT_NODES={NL}

  # 타이완
  tor-tw:
    extends:
      service: tor-nl
    container_name: tor-tw
    environment:
      - EXIT_NODES={TW}

  # 일본
  tor-jp:
    extends:
      service: tor-nl
    container_name: tor-jp
    environment:
      - EXIT_NODES={JP}

  tor:
    image: haproxy:latest
    container_name: tor
    ports:
      - "9050:9050"
      - "8050:8050"
      - "14567:14567"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - tor
    depends_on:
      - tor-tw
      - tor-nl
      - tor-jp
