services:
  android:
    build:
      context: .
    platform: linux/amd64
    devices:
      - /dev/kvm:/dev/kvm
    tty: true
    stdin_open: true
    ports:
      - "5554:5554"
      - "5555:5555"
