version: '3.9'

networks:
  haproxy:
    name: haproxy

services:
  haproxy:
    build:
      context: ./haproxy
    container_name: haproxy
    user: root
    restart: always
    ports:
      - '9050:9050'
      - '1936:1936'
      - '14567:14567'
    networks:
      - haproxy
    depends_on:
      - tor-1
      - tor-2
      - tor-3
      - tor-4
      - tor-5
      - tor-6
      - tor-7
      - tor-8

  tor:
    build:
      context: ./tor
    image: tor
    restart: always
    networks:
      - haproxy

  tor-1:
    extends:
      service: tor
    container_name: tor-1

  tor-2:
    extends:
      service: tor
    container_name: tor-2

  tor-3:
    extends:
      service: tor
    container_name: tor-3

  tor-4:
    extends:
      service: tor
    container_name: tor-4

  tor-5:
    extends:
      service: tor
    container_name: tor-5

  tor-6:
    extends:
      service: tor
    container_name: tor-6

  tor-7:
    extends:
      service: tor
    container_name: tor-7

  tor-8:
    extends:
      service: tor
    container_name: tor-8
